---
title: "linear_models"
author: "Kairui Wang"
date: "2023-11-09"
output: github_document
---

```{r, include = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

Load key packages.

```{r}
library(tidyverse)
library(rvest)
library(p8105.datasets)
```

## Load and clean the Airbnb data

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) |> 
  filter(borough != "Staten Island") |> 
  select(price, stars, borough, neighborhood, room_type)
```

Let's fit a modle!!

```{r}
fit = 
  nyc_airbnb |> 
  lm(price~stars+borough, data = _)
```


Let's look at
__ don't recommend
```{r, include = FALSE, message = FALSE, warning = FALSE}
fit
summary(fit)
summary(fit)$coef
coef(fit)
# fitted.values(fit)
fitted.values(fit)
```

tidy up the output instead

```{r}
fit |> 
  broom::glance()

fit |> 
  broom::tidy() |> 
  mutate(term = str_replace(term, "^borough", "Borough: ")) |> 
  select(term, estimate, p.value) |> 
  knitr::kable(digits = 3)
```


```{r}
fit = 
  nyc_airbnb |> 
  mutate(
    borough = fct_infreq(borough),
    room_type = fct_infreq(room_type)
  ) |> 
  lm(price~stars+borough+room_type, data = _)

fit |> 
  broom::tidy()
```


## Quick look at diagnostics

```{r}
nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  ggplot(aes(x = resid)) +
  geom_density() +
  xlim(-100, 500)

nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  ggplot(aes(x = borough, y = resid)) +
  geom_violin()

nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  ggplot(aes(x = stars, y = resid)) +
  geom_point()
```


## Hypothesis test for categorical rewdictor

fit a "null" and "alternative" model

```{r}
fit_null = lm(price~stars+borough, data = nyc_airbnb)
fit_alternative = lm(price~stars+borough+room_type, data = nyc_airbnb)

anova(fit_null, fit_alternative) |> 
  broom::tidy()
```













